# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a50bd5ae8e664be2b93b03a4b6e72d07b9b8a79f93cfa4c88c2c3d2da3ca4caf7580abb904854896dad4c8f3ed99576681bc64386129f81155781247ad54576

test:
  secret_key_base: 5a8cd34538f42b6e70cdf35cccfb411b0314dca9ce0da45b08d88f171a8892f09ffc6858af80dfb9f6f8f17047cf539e9ba00e7a2a33b4da32fb5cf8ecb4a7d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
